# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # ...

    providers:
        fos_userbundle:
              id: fos_user.user_provider.username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: main
            provider: fos_userbundle
            logout:
                path:   /logout
                target: /main

    access_control:
        - { path: ^/main, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/catalog, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/moder, roles: ROLE_MODER }
        - { path: ^/restore, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_MODER: ROLE_USER
        ROLE_ADMIN: ROLE_MODER