# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.grid_service:
        class:     AppBundle\Service\GridService
        arguments: ['@doctrine.orm.entity_manager']

    category_view:
        class: AppBundle\Service\CategoryToView

    items_on_category_view:
        class: AppBundle\Service\ItemsOnCategoryToView

    item_view:
        class: AppBundle\Service\ItemToView

    receiving_breadcrumbs:
        class: AppBundle\Service\ReceivingBreadcrumbs